language: java
sudo: false
jdk:
- oraclejdk8
os:
- linux
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
script:
- ./gradlew clean test assemble
after_success:
- ./gradlew nomic-dist:bintrayUpload
env:
  global:
  - secure: YdvZ8+ve3h4/xUcMmLRnVCwyM9J2m0GfiDF8sFZz7doujJpd7CGm8sR7etpUzC55uxmwrVFICT9jxCbeYPgHW5GqMq9bgPM9FvQHYWN8K7zMDAg+ycknKlWaFo4OEqRDTIacupSeJXqXIeERvgx4fJYa76tGOUNAAykPvkAZGHAQHXP3KB1+zjN0ZOvmAFK/wryUAnOuSJsdbz/YtrncOr/uExoosDmJMqytJFfFtMxxx9OQE3aP6OiOO1av6/JB3ddXIiZ5kXlBmmG+zf4wPTKeZ8C2Vj2iXKZOqXU+pxfeBl7dtybPLekoWTmbeAdSpQyhHWP9pode+ZMyxcG+DHv/9qYM6xq0E2T77JQXkBWtoGyhVntl+e82bXG9RQ7Ezmqa1njWvjH4HX772EsRdjF5xNXrt1TPXPvEHJUbhiJyrpS50f1cOYUeORfs6ZFQeXZKEMAGQyCwO5y35IuN+w6u3RX7Y0dXmCa5iAE+TbfuZKe5nTBlJBj/bvUc3n6xdQW2P2evbvLxfQlfAE+IAqzCjunoaawdkBAJ4/tMOZLf0iOVUBHXZSe6aZbqO/C1BR9T996jgblp8VEdf37MuvbxS17tdBjPXv6S0+9XgprEH41fE2oWj0koQumuZDYY/qlLkLoTsjSdb4OoZSyC8xb6xKOzGR5DhKBPL6Vbt9g=
  - secure: Y0cyB8NaAt7ZQvweD5O8AWdNC2zZZ3NaIDHmg3yFY/9KJxV5R3UEPOcIo2ORQlKKuX0LwDyUocS6LyN90TBxyagIitdTGwTvfeTb0CNi33fjUAtP48cCCdqi73xTN6LxmP2cjW/J5H8QMsX9oGYHY2k+BCJKrmVtBgn3Gn6kj6HSNovU5ezDC/M99eutczbJn7WZgT/FRAGOYalAVpUk0RVoG3ZGICPvoPpepHvaGIgjNqCI7+W3EJJu++3Tc0DgffOpGX1KJ/D/pxGex5+xoLSZvjXcFwULAOIDRBo22YLgacZLN8c2K8RhRMm8oYcDB/GgfOVjCjYwL+8GENrFfK3krntydc34cgxL8q5yEal1vFDx6NGevlNlXMUCfmbOQizJoCuJuH4sA9zv52IG0DhKdlaGzAs5dHep3g1P1nulJ5ERWYMiI17lrxRU0Rdu/+g6154mBVerD/et37KHlCQbunk9HMjDCxYfT9oAYpqzza+ICED2F9ZD7TDElCYUkZfG+klkNPEU6e74nHtXPfbwND49rbLfGI8V/e0qLsy7t80yAETTaFjKJI0fyrIMlPmdW5qRVOjtat+dpZ6cUfKYahZZCBeOskS+sTNn0oQrsVxzFOb9a/r9Nzsgr9x1wkEGwvfTXLcukfbz0svzC8JfMEtPLk2faFzFk/f786o=
